<?php

/**
 * @file
 * A module exemplifying Drupal coding practices and APIs.
 *
 * This module provides a block that lists all of the
 * installed modules. It illustrates coding standards,
 * practices, and API use for Drupal 7.
 */

/**
 * Implements hook_help().
 */
function first_help($path, $arg) {
  if ($path == 'admin/help#first') {
    return t('A demonstrate module.');
  }
}

/**
 * Implements hook_block_info().
 */
function first_block_info() {
  $blocks = [];
  $blocks['first'] = [
    'info' => t('Fiist Block'),
    'cache' => DRUPAL_NO_CACHE,
  ];
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function first_block_view($block_name = '') {
  if ($block_name == 'first') {
    $lists = module_list();

    // Shaping view content.
    $theme_args = ['items' => $lists, 'type' => 'ol'];
    $content = theme('item_list', $theme_args);

    $block = [
      'subject' => t('Enebeld Module'),
      'content' => $content,
    ];
    return $block;
  }
}
